apiVersion: v1
kind: Service
metadata:
  name: stock-ms-service
  namespace: devops
spec:
  selector:
    app: stock-ms
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8088
  type: NodePort
